version: '2.3'
services:
  app:
      build: .
      command: node app.js
      volumes:
          - .:/app
          - /app/node_modules
      depends_on:
          - postgres

  postgres:
      image: postgres:9.6
      environment:
          POSTGRES_PASSWORD: postgres
      ports:
          - "26001:5432"
