app:
    build: .
    command: node app.js
    volumes:
        - .:/app
        - /app/node_modules
    links:
        - postgres

postgres:
    image: postgres:9.6
    ports:
        - "26001:5432"
